#! /bin/bash

### BEGIN INIT INFO
# Provides:          dropbox
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: dropbox service
# Description:       Run dtopbox service
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting Dropbox..."
    dropbox start
    ;;
  stop)
    echo "Stopping Dropbox..."
    dropbox stop
    sleep 2
    ;;
  status)
    echo "Status Dropbox..."
    dropbox status
    sleep 2
    ;;
  *)
    echo "Usage: /etc/init.d/dbox {start|stop|status}"
    exit 1
    ;;
esac

exit 0
